---

name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 24.2.1-1
        elixir:
          - 1.13.3
        os:
          - ubuntu20.04

    container: "ghcr.io/emqx/emqx-builder/5.0-7:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: build
        run: make rel
      - name: test
        run: mix test

...
