---

name: Build and Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 24.2.1-1
        elixir:
          - 1.13.3
        os:
          - ubuntu20.04

    container: "ghcr.io/emqx/emqx-builder/5.0-8:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: build
        run: make rel
      - name: test
        run: mix test
      - name: upload artifact
        uses: actions/upload-artifact@v3.0.0
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: release
          if-no-files-found: error
          retention-days: 1
          path: |
            _build/prod/plugrelex/elixir_plugin_template/elixir_plugin_template-0.1.0.tar.gz

  release:
    runs-on: ubuntu-20.04
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.0
        with:
          name: release
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            elixir_plugin_template-0.1.0.tar.gz

...
