---

name: Build and Test

on:
  push:
    branches:
      - emqx50
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        otp:
          - 25.3.2-2
        elixir:
          - 1.14.5
        os:
          - ubuntu22.04

    container: "ghcr.io/emqx/emqx-builder/5.2-3:${{ matrix.elixir }}-${{ matrix.otp }}-${{ matrix.os }}"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: make rel
      - name: test
        run: mix test
      - name: upload artifact
        uses: actions/upload-artifact@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: release
          if-no-files-found: error
          retention-days: 1
          path: |
            _build/prod/plugrelex/elixir_plugin_template/elixir_plugin_template-0.1.2.tar.gz

  release:
    runs-on: ubuntu-latest
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: release
      - name: GH Release
        uses: softprops/action-gh-release@v0.1.14
        with:
          files: |
            elixir_plugin_template-0.1.2.tar.gz

...
